[package]
name = "shootem_up"
version = "0.1.0"
authors = ["agate-pris <agate-pris@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
three = "0"
mint = "0"
cgmath = "0.17"
